language: cpp
compiler:
  - gcc
  - clang
before_script:
  - ./configure --enable-version=18,19
branches:
  only:
    - master
notifications:
  recipients:
    - herbert.koelman@me.com
  email:
    on_success: change
    on_failure: always
